language: python
python:
  - "3.4"

install:
  # Install iverilog package.
  - "sudo add-apt-repository -y ppa:mithro/iverilog-backport"
  - "sudo apt-get update"
  - "sudo apt-get install iverilog"
  - "iverilog -v; true"
  # Build the vpi module.
  - "(cd vpi; make; sudo make install)"

script:
  - "python setup.py test"

notifications:
  email: false
  irc:
    channels:
      - chat.freenode.net#m-labs
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Build details : %{build_url}"
